name: Uncrustify Check

# на push проще тестировать
on:
  push

jobs:
  uncrustify-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # последняя версия Uncrustify для ubuntu - 0.72; для arch - 0.77.1
    # чтобы настройки на машине разработчика совпадали с настройками при проверке
    # явно подтягиваем версию uncrustify-0.77.1
    # TODO: этот шаг занимает много времени, возможно можно кэшировать?
    - name: Set up Uncrustify
      run: |
        # sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/uncrustify/uncrustify/archive/uncrustify-0.77.1.tar.gz
        tar -xzvf uncrustify-0.77.1.tar.gz
        cd uncrustify-uncrustify-0.77.1
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

    # Так как файл с конфигурационными настройками uncrustify.cfg не хранится
    # в каждом репозитории, нужно подтянуть его отсюда:
    # https://github.com/QCoreTech/format.cmake/blob/master/uncrustify.cfg
    # - name: Download Uncrustify Config
    #   run: |
    #     curl -O -L https://github.com/QCoreTech/format.cmake/blob/master/uncrustify.cfg

    # Проверка форматирования:
    # - если все файлы проекта отформатированы, проверка будет пройдена успешно;
    # - если для каких-то файлов форматирование не применено - проверка провалится
    # и будет выведен список файлов, не соотвествующих форматированию.
    # TODO: файл с настройками должен подтягиваться из стороннего приватного репозитория,
    # сейчас он лежит в корневой директории проекта.
    # Пример вывода при неуспехе:
    # Uncrustify check failed for the following files:
    # FAIL: ./src/main.cpp (File size changed from 1824 to 1664)
    - name: Run Uncrustify Check
      run: |
        result=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \; 2>&1)
        if echo "$result" | grep -q "FAIL" ; then
          echo "Uncrustify check failed for the following files:"
          echo "$result" | grep "FAIL"
          exit 1
        else
          echo "Uncrustify check passed for all files."
          exit 0
        fi

    # Здесь была попытка удалить файл с конфигурацинными настройками,
    # т.к. кажется он сам не удаляется, а эти файлы копятся в склонированном репозитории
    # - name: Remove Uncrustify Config
    #   run: |
    #     rm $GITHUB_WORKSPACE/uncrustify.cfg





