name: Uncrustify Check

on:
  push

jobs:
  uncrustify-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Uncrustify
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/uncrustify/uncrustify/archive/uncrustify-0.77.1.tar.gz
        tar -xzvf uncrustify-0.77.1.tar.gz
        cd uncrustify-uncrustify-0.77.1
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

    - name: Run Uncrustify Check
      run: |
        result=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \;)

        if [[ $result == *"FAIL"* ]]; then
          echo "Uncrustify check failed for the following files:"
          echo "$result" | grep "FAIL"
          exit 1
        fi

    # - name: Run Uncrustify Check
    #   run: |
    #     result=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \; | grep -E "FAIL")
    #     if [ -n "$result" ]; then
    #       echo "Uncrustify check failed for the following files:"
    #       echo "$result"
    #       exit 1
    #     else
    #       echo "Uncrustify check passed for all files."
    #     fi

    # - name: Run Uncrustify Check
    #   run: |
    #     find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -exec uncrustify --check -c uncrustify.cfg {} \;

    # - name: Run Uncrustify Check
    #   run: |
    #     failed_files=""
    #     while IFS= read -r -d $'\0' file; do
    #       uncrustify --check -c uncrustify.cfg "$file"
    #       if [ $? -ne 0 ]; then
    #         failed_files="$failed_files $file"
    #       fi
    #     done < <(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -print0)
    #
    #     if [ -n "$failed_files" ]; then
    #       echo "Файл(ы):$failed_files не соответствуют настройкам форматирования uncrustify."
    #       exit 1
    #     fi


    # - name: Run Uncrustify Check
    # run: |
    #     failed_files=""
    #     while IFS= read -r -d $'\0' file; do
    #         uncrustify --check -c uncrustify.cfg "$file" >/dev/null 2>&1
    #         if [ $? -ne 0 ]; then
    #             failed_files="$failed_files $file"
    #         fi
    #     done < <(find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./uncrustify-uncrustify-0.77.1/*" -print0)
    #
    #     if [ -n "$failed_files" ]; then
    #         echo "Файл(ы):$failed_files не соответствуют настройкам форматирования uncrustify."
    #         exit 1
    #     fi
