name: Uncrustify Check

on:
  push:
    branches:
      - '*'

jobs:
  uncrustify-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Uncrustify Config from External Repository
      run: |
        curl -O -L https://raw.githubusercontent.com/QCoreTech/format.cmake/master/uncrustify.cfg
        ls -al  # Optional: Display the downloaded files

    - name: Install Uncrustify
      run: |
        sudo apt-get update
        sudo apt-get install -y uncrustify

    - name: Make Script Executable
      run: chmod +x .github/workflows/uncrustify-check.sh

    - name: Run Uncrustify Check
      run: ./.github/workflows/uncrustify-check.sh

    - name: Display Files with Incorrect Formatting
      run: |
        if [ -n "$(git diff --name-only)" ]; then
          echo "Files with incorrect formatting:"
          git diff --name-only
          exit 1
        else
          echo "All files conform to the code formatting rules."
        fi
