name: Uncrustify Check

on:
  push

jobs:
  uncrustify-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Uncrustify
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/uncrustify/uncrustify/archive/uncrustify-0.77.1.tar.gz
        tar -xzvf uncrustify-0.77.1.tar.gz
        cd uncrustify-uncrustify-0.77.1
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

    - name: Run Uncrustify Check
      run: |
        find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -exec uncrustify --check -c uncrustify.cfg {} \;
