name: Uncrustify Check

on:
  push

jobs:
  uncrustify-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Uncrustify
      run: |
        sudo apt-get update
        sudo apt-get install -y uncrustify

    - name: Run Uncrustify Check
      run: |
        find . -type f \( -name "*.cpp" -o -name "*.h" \) -exec uncrustify --check -c uncrustify.cfg {} \;
